version: "3"
services:
  app:
    build:
      context: .
    container_name: "app_service"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 main.py"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    container_name: "db_service"
    ports:
      - "5430:5432"
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db_scripts:
  postgres_data:
